.\" 
.\" Copyright (c) 2009 Gordon D. Carrie
.\" All rights reserved
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.2 $ $Date: 2009/11/06 22:51:35 $
.\"
.TH sigmet_raw 3 "Sigmet raw product"
.SH NAME
sigmet_raw \- access Sigmet raw product volumes
.SH SYNOPSIS
.nf
\fBsigmet_raw\fP \fBtypes\fP
\fBsigmet_raw\fP \fBvolume_headers\fP \fIraw_volume\fP
\fBsigmet_raw\fP \fBray_headers\fP \fIraw_volume\fP
\fBsigmet_raw\fP \fBdata\fP [\fItype\fP] [\fIs\fP] [\fIr\fP] [\fIb\fP] [\fIraw_volume\fP]
\fBsigmet_raw\fP \fBbin_outline\fP \fIs\fP \fIr\fP \fIb\fP \fIraw_volume\fP
.fi
.SH DESCRIPTION
The \fBsigmet_raw\fP application reads and prints information
from Sigmet raw product volumes.  In the command descriptions below,
\fIraw_volume\fP must be a Sigmet raw product volume.  If absent
or "\fB-\fP", the command will read a raw product volume from standard
input.  Option \fItype\fP refers to the short name of a Sigmet data type,
e.g. "\fBDB_DBZ\fP".  Indeces start with \fB0\fP.
.TP
\fBsigmet_raw\fP \fBtypes\fP
Prints a list of all possible Sigmet data types.  Output lines have form:
.sp 1
.ti +4
\fIDB_XXX\fP \fB|\fP \fIDescription\fP
.sp 1
.TP
\fBsigmet_raw\fP \fBvolume_headers\fP \fIraw_volume\fP
Reads and prints volume headers.  Ray headers and data are not printed.
Output lines have form:
.sp 1
.ti +4
\fIvalue\fP \fB|\fP \fIhierarchy\fP \fB|\fP \fIdescriptor\fP
.sp 1
In this context, \fIhierarchy\fP refers to the Sigmet data
structures that contain the member.  For a hierarchy with two
levels, it would look like
.sp 1
.ti +4
\fI<struct1>.<struct2>.member\fP.
.sp 1
Be aware that the same member might reside in several structure
hierarchies.  See the IRIS Programmers Manual for details.
.TP
\fBsigmet_raw\fP \fBray_headers\fP \fIraw_volume\fP
Reads and prints ray times, azimuths, and tilts.  Volume headers
and data are not printed.
.TP
\fBsigmet_raw\fP \fBdata\fP \fIraw_volume\fP
Reads and prints all volume data as text. Headers are not printed.
.TP
\fBsigmet_raw\fP \fBdata\fP \fItype\fP \fIraw_volume\fP
Reads and prints data for data type \fItype\fP as text.
.TP
\fBsigmet_raw\fP \fBdata\fP \fItype\fP \fIs\fP \fIraw_volume\fP
Reads and prints data for data type \fItype\fP, sweep \fIs\fP as text.
.TP
\fBsigmet_raw\fP \fBdata\fP \fItype\fP \fIs\fP \fIr\fP \fIraw_volume\fP
Reads and prints data for data type \fItype\fP, sweep \fIs\fP,
ray \fIr\fP as text.
.TP
\fBsigmet_raw\fP \fBdata\fP \fItype\fP \fIs\fP \fIr\fP \fIb\fP \fIraw_volume\fP
Reads and prints data for data type \fItype\fP, sweep \fIs\fP,
ray \fIr\fP, bin \fIb\fP as text.
.TP
\fBsigmet_raw\fP \fBbin_outline\fP \fIs\fP \fIr\fP \fIb\fP \fIraw_volume\fP
Reads and prints the corners of bin \fIs\fP \fIr\fP \fIb\fP as
"\fIlon1\ lat1\ lon2\ lat2\ lon3\ lat3\ lon4\ lat4\fP."
.SH SEE ALSO
IRIS Programmer's Manual (http://sigmet.com)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
