.\"
.\" Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\"     * Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"     * Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
.\" TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\" PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"
.\" Please address questions and feedback to dev0@trekix.net
.\"
.\" $Revision: 1.35 $ $Date: 2012/04/27 20:27:02 $
.\"
.Dd $Mdocdate$
.Dt SIGMET_RAW 1
.Os Unix
.Sh NAME
.Nm sigmet_raw
.Nd interact with data from Sigmet raw volumes
.Sh SYNOPSIS
.Nm sigmet_raw
.Cm load
.Ar raw_product_file
.Ar socket
.Nm sigmet_raw
.Ar command
.Op options
.Ar socket
.Sh DESCRIPTION
The 
.Nm sigmet_raw
command reads, stores, and manipulates data from Sigmet raw product volumes.
Its behavior is determined the the first word after
.Nm sigmet_raw .
The following forms are recognized:
.Bl -ohang
.It Nm sigmet_raw Cm data_types Op socket
Prints a list of Sigmet data types. At a minimum, this command lists the
Sigmet data types from the Iris Programmer's Manual. With
.Ar socket ,
it will also list any additional data types known to a
.Nm sigmet_raw
daemon associated with the socket, as described below. Output lines will have
form:
.Bd -literal -offset indent
\fIDB_field\fP | \fIDescription\fP | \fIunit\fP | \fBused\fP
\fIDB_field2\fP | \fIDescription2\fP | \fIunit\fP | \fBunused\fP

.Ed
If the last word is
.Qo
used
.Qc
there is a field for the data type in the volume.
If the last word is
.Qo
unused
.Qc
the data type is known but not represented in the volume.
.It Nm sigmet_raw Cm good Ar raw_file Op socket
Returns true if standard input provides a navigable Sigmet raw product.
The raw product may not contain any useful meta-data or data, and nothing
is stored. This command only checks volume integrity. If
.Ar socket
is given, this command reports on the integrity of the volume belonging to a
.Nm sigmet_raw
daemon, described below.
.It Nm sigmet_raw Cm load Ar raw_file Ar socket
Starts a daemon that loads a Sigmet raw product from file
.Ar raw_file .
The daemon then listens for information and action requests from a socket named
.Ar socket
in the current working directory (note the leading dot in the socket name). It
also writes log messages to local file
.Li .sigmet.log
and error messages to
.Li .sigmet.err .
.El
.Sh VOLUME COMMANDS
The following commands act on a daemon launched with a call to
.Nm sigmet_raw Cm load .
Current working directory must contain the associated
.Ar socket
socket.
.Pp
Sweep, ray, and bin indeces start with
.Li 0 .
.Bl -ohang
.It Nm sigmet_raw Cm unload Ar socket
Terminates the daemon.  Upon exit, the daemon deletes
.Ar socket
although
.Li .sigmet.log
and
.Li .sigmet.err
remain.
.It Nm sigmet_raw Cm pid Ar socket
Prints the process identifier of daemon.
.It Nm sigmet_raw Cm volume_headers Ar socket
Prints volume headers.  Values are those obtained from product header and ingest
data header of the raw file.  Ray headers and data are not printed.  Output lines
have form:
.Bd -filled
    \fIvalue\fP \fB|\fP \fIhierarchy\fP \fB|\fP \fIdescriptor\fP

.Ed
In this context, hierarchy refers to the Sigmet data
structures described in the IRIS Programmer's Manual that contain the member,
e.g.
.Bd -filled
    \fI<ingest_header>.<ingest_configuration>.num_sweeps\fP

.Ed
This format is easy for other processes to filter and manipulate, but hard to
read on a screen. For a more readable list, filter with something like:
.Bd -filled
    \fBsigmet_raw\fP \fBvolume_headers\fP \fIraw_file\fP \fB\ \\
    | awk -F\ \&| '{printf "%s = %s\\n %s\\n\\n", $2, $1, $3}'\fP

.Ed
Be aware that the same member might reside in several structure
hierarchies. See the IRIS Programmer's Manual for details.
.It Nm sigmet_raw Cm vol_hdr Ar socket
Prints commonly used volume headers. Output will look like:
.Bd -filled
    \fBsite_name\fP="\fIsite_name_from_setup\fP"
    \fBradar_lon\fP=\fIlongitude_degrees\fP
    \fBradar_lat\fP=\fIlatitude_degrees\fP
    \fBtask_name\fP="\fItask_name\fP"
    \fBtypes\fP="\fItype_name\fP \fItype_name\fP ..."
    \fBnum_sweeps\fP=\fIinteger\fP
    \fBnum_rays\fP=\fIinteger\fP
    \fBnum_bins\fP=\fIinteger\fP
    \fBrange_bin0\fP=\fIinteger_cm\fP
    \fBbin_step\fP=\fIinteger_cm\fP

.Ed
.It Nm sigmet_raw Cm near_sweep Ar angle Ar socket
Prints the index (base zero) of the sweep with sweep angle nearest
.Ar angle
degrees.
.It Nm sigmet_raw Cm sweep_headers Ar socket
Lists times and angle for each sweep, as reported by the sweep headers in the
volume. For each sweep, this command prints a line of form:
.Bd -filled
    \fBsweep\fP \fIindex\fP \fIYYYY\fP\fB/\fP\fIMM\fP\fB/\fP\fIDD\fP \fIHH\fP\fB:\fP\fIMM\fP\fB:\fP\fISS\fP   \fIangle\fP
.Ed
Unusable sweep time is printed as:
\fI0000\fP\fB/\fP\fI00\fP\fB/\fP\fI00\fP \fI00\fP\fB:\fP\fI00\fP\fB:\fP\fI00\fP
.It Nm sigmet_raw Cm ray_headers Ar socket
Prints ray times and beginning and ending azimuths and tilts for all rays
in the volume. For each ray, this command prints a line of form:
.Bd -filled
    \fBsweep\fP\ \fIindex\fP\ \fBray\fP\ \fIindex\fP\ |\ \fIYYYY\fP/\fIMM\fP/\fIDD\fP\ \fIHH\fP:\fIMM\fP:\fISS.SSS\fP\ |\ \fBaz\fP\ \fIstart\fP\ \fIend\fP\ |\ \fBtilt\fP\ \fIstart\fP\ \fIend\fP
.Ed
.It
.Xo
.Nm sigmet_raw
.Cm new_field
.Ar data_type
.Op Fl v Ar value
.Op Fl d Ar description
.Op Fl v Ar unit
.Ar socket
.Xc
Adds a field named
.Ar data_type
to the volume.
Optional
.Ar description
describes the new field.
Optional
.Ar unit
provides a unit. This is not implicitly used in any calculation. If no
.Ar value
is given, all bins are set to an unusable value in the new field.  If present,
.Ar value
is interpreted as follows:
.Bl -ohang -offset indent
.It Ar scalar
All bins are set to
.Ar scalar .
.It Cm r_beam
Each bin value is set to distance in meters along the beam.
.It Ar data_type
Values from field
.Ar data_type ,
which must already exist in the volume, are copied to the new field.
.El
.It Nm sigmet_raw Cm del_field Ar data_type Ar socket
Removes the specified field from the volume.
.It Nm sigmet_raw Cm size Ar socket
Prints the amount of memory the volume is using for headers and data.
.It Nm sigmet_raw Cm set_field Ar data_type Ar value Ar socket
Assigns a value to a field.
.Ar value
must be one of
.Bl -ohang -offset indent
.It Ar scalar
All bin values are set to
.Ar scalar .
.It Cm r_beam
Each bin value is set to distance in meters along the beam.
.It Ar data_type2
Values from field
.Ar data_type2 ,
which must already exist in the volume, are copied to the new field.
.El
.It Nm sigmet_raw Cm add Ar data_type Ar value Ar socket
Adds a value or values to the field of
.Ar data_type .
The sums replace the original bin values for
.Ar data_type ,
which are lost.
.Ar value
must be one of:
.Bl -ohang -offset indent
.It Ar scalar
All bin values for field
.Ar data_type
are incremented by
.Ar scalar .
.It Ar data_type2
For each bin, the value of the
.Ar data_type
field is incremented by the bin's
.Ar data_type2
value. A field of
.Ar data_type2
must already exist in the volume.
.El
.It Nm sigmet_raw Cm sub Ar data_type Ar value Ar socket
Subtracts a value or values from the field of
.Ar data_type .
The differences replace the original bin values for
.Ar data_type ,
which are lost.
.Ar value
must be one of
.Bl -ohang -offset indent
.It Ar scalar
All bin values for field
.Ar data_type
are decremented by
.Ar scalar .
.It Ar data_type2
For each bin, the value of the
.Ar data_type
field is decremented by the bin's
.Ar data_type2 ,
value. A field of
.Ar data_type2
must already exist in the volume.
.El
.It Nm sigmet_raw Cm mul Ar data_type Ar value Ar socket
Multiplies the field of
.Ar data_type
by a value or values. The products replace the original bin values for
.Ar data_type ,
which are lost.
.Ar value
must be one of:
.Bl -ohang -offset indent
.It Ar scalar
All bin values are multiplied by
.Ar scalar .
.It Ar data_type2
For each bin, the value of the
.Ar data_type
field is multiplied by the value for the
.Ar data_type2
field. A field of
.Ar data_type2
must already exist in the volume.
.El
.It Nm sigmet_raw Cm div Ar data_type Ar value Ar socket
Divides the field of
.Ar data_type
by a value or values. The quotients replace the original bin values for
.Ar data_type ,
which are lost.
.Ar value
must be one of:
.Bl -ohang -offset indent
.It Ar scalar
All bin values are divided by
.Ar scalar .
.It Ar data_type2
For each bin, the value of the
.Ar data_type
field is divided by the value for the
.Ar data_type2
field. A field of
.Ar data_type2
must already exist in the volume.
.El
.It Nm sigmet_raw Cm log10 Ar data_type Ar socket
In each bin, replaces the
.Ar data_type
value with its common logarithm.
.It Nm sigmet_raw Cm incr_time Ar socket
Adds
.Ar dt
seconds to all times in the volume, sweep, and ray headers.
.It Nm sigmet_raw Cm data Ar socket
Prints all bin values for the volume to standard output as text.
.It Nm sigmet_raw Cm data Ar data_type Ar socket
Prints all bin values for
.Ar data_type
to standard output as text.
.It Nm sigmet_raw Cm data Ar data_type Ar s Ar socket
Prints all bin values for sweep
.Ar s ,
field
.Ar data_type
to standard output as text.
.It Xo
.Nm sigmet_raw Cm data
.Ar data_type
.Ar s
.Ar r
.Ar socket
.Xc
Prints all bin values for ray
.Ar r ,
sweep
.Ar s ,
field
.Ar data_type
to standard output as text.
.It Xo
.Nm sigmet_raw Cm data
.Ar data_type
.Ar s
.Ar r
.Ar b
.Ar socket
.Xc
Prints the value of bin
.Ar b ,
ray
.Ar r ,
sweep
.Ar s ,
field
.Ar data_type
to standard output as text.
.It Nm sigmet_raw Cm bdata Ar data_type Ar s Ar socket
Prints data for field
.Ar data_type ,
sweep index
.Ar s ,
to standard output as a binary stream. Output will have dimensions ray by bin.
Values will be native floats. Missing values will be given as the value returned
by
.Fn Sigmet_NoData .
See
.Xr sigmet_data 3 .
.It Xo
.Nm sigmet_raw Cm bin_outline Ar s Ar r Ar b Ar socket
.Xc
Prints the longitudes and latitudes, in degrees, of the corners of sweep
.Ar s ,
ray
.Ar r ,
bin
.Ar b .
Output will be of form:
.Bd -filled -offset indent
\fIlat1 lon2 lat2 lon3 lat3 lon4 lat4\fP
.Ed
.It Nm sigmet_raw Cm radar_lon Ar lon Ar socket
Sets the radar longitude to
.Ar lon
degrees.
.It Nm sigmet_raw Cm radar_lat Ar lat Ar socket
Sets the radar latitude to
.Ar lat
degrees.
.It Nm sigmet_raw Cm shift_az Ar socket
Adds
.Ar daz
degrees to all azimuths in the volume.
.It Xo
.Nm sigmet_raw
.Cm dorade
.Op s
.Ar socket
.Xc
Creates DORADE sweep files. If
.Ar s
is absent or
.Qo
all
.Qc ,
this command will make DORADE sweep files for all sweeps in the volume.
Otherwise, it will make one sweep file for sweep
.Ar s .
.It Xo
.Nm sigmet_raw
.Cm outlines
.Op Fl b
.Op Fl f
.Ar data_type
.Ar s
.Ar min
.Ar max
.Ar out_file
.Ar socket
.Xc
Prints outlines of bins for data type
.Ar data_type
sweep
.Ar s
for which the field has values
.Ar min
.Li <=
value
.Li <
.Ar max .
The outlines are printed to file
.Ar out_file .
If
.Ar out_file
is
.Li - ,
they are printed to standard output of the sigmet_raw client. By default,
output is a text stream. For a PPI sweep, each line of output contains the
corners of one bin as
.Bd -literal -offset indent
lon1 lat1 lon2 lat2 lon3 lat3 lon4 lat4

.Ed
where lon denotes longitude in decimal degrees east and lat denotes latitude
in decimal degrees north.
For a RHI sweep, each line of output contains the corners of one bin as
.Bd -literal -offset indent
rng1 alt1 rng2 alt2 rng3 alt3 rng4 alt4

.Ed
where rng denotes range along the ground to the point below the corner, in
meters, and alt denotes height above ground in meters.
Bin outlines are right handed polygons. If
.Fl b
is present, output is a native binary stream instead of text, and longitudes
and latitudes for PPI bins are given in radians. If
.Fl f
is present, outlines are expanded so that they touch, if necessary.
Otherwise, the bin outline stated in the file is used, which might
result in gaps between adjacent bins.
.El
.Sh SEE ALSO
.Xr sigmet_data 3 ,
.Xr sigmet_vol 3
.Rs
.%B IRIS Programmer's Manual
.Re
.Sh AUTHOR
Gordon Carrie (dev0@trekix.net)
