.\" 
.\" Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\"     * Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"     * Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
.\" TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\" PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.4 $ $Date: 2011/11/28 16:57:49 $
.\"
.TH tm_calc 1 "time conversions"
.SH NAME
tm_calc \- convert between calendar-clock times and Julian dates.
.SH SYNOPSIS
.nf
\fBtm_calc\fP \fBcaltojul\fP [\fB-f\fP \fIformat\fP] \fIyear\fP \fImonth\fP \fIday\fP \fIhour\fP \fIminute\fP \fIsecond\fP
\fBtm_calc\fP \fBjultocal\fP [\fB-f\fP \fIformat\fP] \fIjulian_day\fP
.fi
.SH DESCRIPTION
The \fBtm_calc\fP command converts between calendar-clock times and Julian dates.

\fBtm_calc\fP\ \fBcaltojul\fP prints the Julian day corresponding to
\fIyear\fP \fImonth\fP \fIday\fP \fIhour\fP \fIminute\fP \fIsecond\fP.  Optional
\fIformat\fP should be a string that would instruct \fBprintf\fP to print a
float value.

\fBtm_calc\fP \fBjultocal\fP prints the year, month, day, hour, minute, and second
corresponding to Julian day \fIjulian_day\fP.  Optional \fIformat\fP should be
a string that would instruct \fBprintf\fP to print six float values.
.SH SEE ALSO
\fBtm_calc_lib\fP (3), \fBprintf\fP (1)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
