#!/bin/sh
#
#	sigmet_raw.sh --
#		Send a command to a sigmet_raw daemon. Print the result.
#
# Usage:
#	sigmet_raw.sh in_fifo out_fifo command [args ...]
#
# A sigmet_raw process running in daemon mode should be read commands from
# in_fifo and printing results to out_fifo.

if [ $# -lt 3 ]
then
    echo "Usage: $0 in_fifo out_fifo command [args ...]" 1>&2
    exit 1
fi
in=$1
out=$2
shift
shift
printf "open %s\n%s\nclose\n" "$out" "$*" > "$in"
cat $out
