#!/bin/sh

# Locate Sigmet volumes
sig_dir=$1
if ! test -d "$sig_dir"
then
    echo "$sig_dir not a directory"
    exit 1
fi

# Create local tmp
mkdir -p tmp
# rm -f tmp/*

# sigmet_raw should be listening to named pipe created with
#	mkfifo $sf
#	./sigmet_raw $sf > tmp/sigmet_raw.out &
sf="tmp/sigmet_raw.in"
if ! test -p $sf
then
    echo No pipe for sigmet_raw commands
    exit 1
fi

# Uncompress volumes and feed to sigmet_raw
for v in ${sig_dir}/*RAW*.gz
do
    if test -f $v
    then
	echo "Reading $v"
	printf 'read %s\ndata DB_DBZ 0 4 30\n' $v > $sf
	echo "Done with $v"
    fi
done
