#!/bin/sh
#
#	sigmet_outlines --
#		Print color specifiers and bin outlines for a sweep
#
# Usage:
#	sigmet_outlines data_type sweep_index proj socket
# where:
#	data_type	- data type, e.g. DB_DBZ. Current directory or
#			  directory specified by SIGMET_RAW_COLOR_DIR
#			  must contain a file named ${data_type}.clrs
#			  with lines of form:
#			  "lower_bound color_specifier upper_bound"
#	sweep_index	- sweep index. First sweep is 0.
#	proj		- command that transforms coordinate pairs
#			  read from standard input. Transformed values
#			  must be printed to standard output.
#			  If "", outline coordinates are not transformed
#			  (use for rhi).
#	socket		- socket for a sigmet_raw daemon
#
# Output will be:
#	one line of form "color: color_specifier"
#	stream of outlines from the "sigmet_raw outlines" command.
#
# See sigmet_raw (1).
# 
########################################################################
#
# Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net
# 
########################################################################

# Parse command line
if [ $# -ne 4 ]
then
    echo Usage: $0 data_type sweep_index projection socket > /dev/stderr
    exit 1
fi
data_type=$1
sweep_index=$2
proj="$3"
socket="$4"
color_dir=${SIGMET_RAW_COLORS:-"."}
color_fl=${color_dir}/${data_type}.clrs
if ! test -f $color_fl
then
    echo "Could not find color file $color_fl" > /dev/stderr
    exit 1
fi
if test "$proj"
then
    proj="| $proj"
fi
egrep '([0-9.+-]+|INF|inf) #[0-9A-Fa-f]+ ([0-9.e+-]+|INF|inf)' $color_fl \
| while read min color max
do
    printf 'color: %s\n' $color
    eval sigmet_raw outlines $data_type $sweep_index $min $max - $socket $proj
done
exit 0
