#!/bin/sh
#
#	sigmet_rawd --
#		Start a sigmet_raw daemon, send a command to it,
#		clean up, and exit.
#
# Usage:
#	sigmet_rawd raw_file args ...
#
# Create a directory in local directory named sigmet_raw_file
# Make it current working directory.
# Load the volume with sigmet_raw.
# Run "args ..." (should be an interactive shell).
# Unload sigmet_raw when "args ..." exits.
#
# Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net


if [ $# -lt 2 ]
then
    echo Usage: $0 args ... raw_file
    exit 1
fi
for a in "$@"
do
    cmd="$cmd $prev"
    prev=$a
done
raw_fl="$a"
sock=.`echo $raw_fl | sed -e 's!.*/!!' -e 's/\.gz$//' -e 's/\.bz2$//'`
trap "sigmet_raw unload -f $sock 2> /dev/null" EXIT
trap "sigmet_raw unload -f $sock 2> /dev/null;exit" HUP
if ! test -S "$sock"
then
    if echo $raw_fl | grep -q '\.gz$'
    then
	gunzip -c $raw_fl | sigmet_raw load - $sock > /dev/null || exit 1
    elif echo $raw_fl | grep -q '\.bz2$'
    then
	bzcat -c $raw_fl | sigmet_raw load - $sock > /dev/null || exit 1
    else
	sigmet_raw load $raw_fl $sock > /dev/null || exit 1
    fi
fi
sigmet_raw $cmd $sock
sigmet_raw unload -f $sock
/bin/rm -f ${sock}.err ${sock}.log
