#!/bin/sh
#
#	sigmet_cleanup --
#		Clean up when a script that uses a sigmet_raw daemon
#		exits.
#
# Usage:
#	sigmet_cleanup socket
# where:
#	socket is a sigmet_raw daemon socket. See sigmet_raw (1).
#
# Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net

# Parse command line
if [ $# -ne 1 ]
then
    echo Usage: $0 socket > /dev/stderr
    exit 1
fi
sock=$1

# Post to semaphores, if any
if test $SIGMET_SEM_PROC
then
    clsem 1 $SIGMET_SEM_PROC 2> /dev/null
fi
if test "$SIGMET_RAW_VOL_SZ" -a "$SIGMET_SEM_MEM"
then
    clsem $SIGMET_RAW_VOL_SZ $SIGMET_SEM_MEM 2> /dev/null
fi

# Tell daemon to exit
sigmet_raw unload -f $sock 2> /dev/null
