#!/bin/sh
#
# sigmet_svg --
#	Send an image of a sweep to standard output.
#
# Usage:
#	sigmet_svg data_type sweep_index socket
# where:
#	data_type	- data type (e.g. DB_DBZ, DB_ZDR).
#	sweep_index	- index of sweep in volume. First sweep is 0.
#	socket		- socket that communicates with a sigmet_raw daemon.
#
# Environment variables:
#	SIGMET_RAW_PROJ		- command that reads longitude latitude
#				  values from standard input and prints
#				  x y values to standard output.
#				  Must be set for ppi sweeps.
#				  Not used for rhi sweeps.
#	SIGMET_RAW_COLORS	- path to directory with color table
#				  files. For each data type DB_XXX
#				  this directory must contain a file
#				  named DB_XXX.clrs with output from
#				  the raster_clrs program appropriate
#				  for the data type. Defaults to
#				  current working directory.
#	SIGMET_RAW_FILL		- if set, then outlines are drawn using the 
#				  "-f" option. See sigmet_raw (1).
#
# The svg code for the image goes to standard output.  Output coordinates will
# be regular cartesian coordinates with origin determined by the output from
# the sigmet_raw outlines command and SIGMET_RAW_PROJ, if defined.
# Output should be wrapped in svg code that imposes suitable scaling, offsets,
# and transformations for the projection display (recall that svg starts
# assuming y increases downward from top of image).
#
# Copyright (c) 2012, Gordon D. Carrie. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net

# Parse command line
if [ $# -ne 3 ]
then
    echo Usage: $0 data_type sweep_index socket 1>&2
    exit 1
fi
data_type=$1
sweep_index=$2
sock="$3"
color_dir=${SIGMET_RAW_COLORS:-"."}
color_fl=${color_dir}/${data_type}.clrs
if ! test -f "$color_fl"
then
    echo "Could not find color file $color_fl" 1>&2
    exit 1
fi
proj_cmd=${SIGMET_RAW_PROJ:-"cat"}
if test "$SIGMET_RAW_FILL"
then
    fill="-f"
fi

# Print SVG outline elements for the sweep.
cat $color_fl \
| egrep '([0-9.+-]+|INF|inf) #[0-9A-Fa-f]+ ([0-9.e+-]+|INF|inf)' \
| while read min color max
do
    echo sigmet_raw outlines $fill -- $data_type $sweep_index $min $max - "$sock"
done
exit 0
