#!/bin/sh
#
#	sigmet_raw_load --
#		Start a sigmet_raw daemon
# Usage:
#	sigmet_raw_load raw_file
# where:
#	raw_file is the path to a file containing sigmet raw product volume.
#
# If necessary, this script will load a sigmet_raw daemon, which will listen
# to a socket in the current working directory named for raw_file. It prints
# the name of the socket.
#
# If current working directory already contains a socket named for raw_file,
# it just prints the socket name and exits.
#
# Optional environment variables:
#	SIGMET_CORRECTIONS		- name of a file with correction
#					  specifiers.  Script sigmet_correct
#					  should be in current path. See
#					  sigmet_correct for format.
#
# Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net

# Parse the command line
if [ $# -ne 1 ]
then
    echo "Usage: $0 raw_file" > /dev/stderr
    exit 1
fi
raw_fl=$1

# Identify the socket. Do nothing if it already exists. Otherwise, load
# the volume and apply corrections, if any.
sock=`echo $raw_fl | sed -e 's!.*/!!' -e 's/\.gz$//' -e 's/\.bz2$//'`
if ! test -S $sock
then
    sigmet_raw load $raw_fl $sock > /dev/null || exit 1
    if test $SIGMET_CORRECTIONS
    then
	sigmet_correct $SIGMET_CORRECTIONS || exit 1
    fi
fi
echo $sock
exit 0
