#!/bin/sh
#
#	sigmet_svg_doc --
#		Create a SVG image of a Sigmet sweep with axes and a color
#		legend.
#
# Requires:
#	sigmet_raw
#	sig_raw
#	pisa
#
# Usage:
#	sigmet_svg [-f] [-b bounds] [-w pixels] [-z pixels] [-l pixels] 
#		[-m top=pixels[,left=pixels]] [-j path] --
#		data_type colors_file sweep_angle volume_file
# where:
#	-f		- fill gaps between adjacent rays.
#	-b		- Limits of plot in plot coordinates (not display
#			  coordinates). bounds must be a string of form
#			  x_min=value,x_max=value,y_min=value,y_max=value
#			  Does not have to give all values. For values not
#			  given, default is to use sweep bounds. Units are
#			  same as sigmet_raw sweep_bnds command.
#	-w		- document width, pixels
#	-z		- font size, pixels
#	-l		- width of color cells in legend, pixels
#	-m		- margins around plot area, given as
#			  top=value,left=value. Right and bottom margins
#			  are determined from font and legend sizes.
#	-j		- path to a Javascript file. Output will include a
#			  script element that refers to the script.
#	-o		- name of output file. If none is given, SVG output
#			  goes to a file with a suitable name. If output
#			  goes to a file, script prints the name of the file
#			  to standard output. If output file name is "-",
#			  SVG goes to standard output.
#	data_type	- Sigmet data type, e.g. DB_DBZ
#	colors_file	- specify color for each data interval. Should be
#			  formatted for sigmet_raw outlines command.
#	sweep_angle	- desired tilt or azimuth. Image will show sweep
#			  nearest sweep_angle.
#	volume_file	- either a path that sigmet_raw can read, or a fifo
#			  that provides commands to a sigmet_raw daemon.
#
# If successful, this script will create a SVG file
# with an image of the sweep closest to the given sweep angle.
#
# Copyright (c) 2012, Gordon D. Carrie. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net
#
#	$Revision: 1.3 $ $Date: 2014/10/29 20:26:24 $

# This function checks whether a value is a number
check_num() {
    name="$1"
    val="$2"
    if ! test $val
    then
	printf "%s not set\n" "$name" 1>&2
	exit 1
    fi
    if ! printf '%g' $val > /dev/null 2>&1
    then
	printf "$0: expected number for %s, got %s\n" "$name" "$val" 1>&2
	exit 1
    fi
}

# Defaults
fill=
x_min=
x_max=
y_min=
y_max=
doc_width=1400
font_sz=18
legend_width=64
top=48
left=80
js_fl=
out_fl=
prx=6					# Precision in labels

# Parse command line
while getopts :fb:w:z:l:m:j:o: opt
do
    case "$opt"
    in
	f)
	    fill="-f"
	    ;;
	b)
	    eval `echo "$OPTARG" | sed 's/,/;/g'`
	    bnds="-b $OPTARG"
	    ;;
	w)
	    doc_width=$OPTARG
	    ;;
	z)
	    font_sz=$OPTARG
	    ;;
	l)
	    legend_width=$OPTARG
	    ;;
	m)
	    eval `echo $OPTARG | sed 's/,/;/g'`
	    ;;
	j)
	    js_fl="$OPTARG"
	    ;;
	o)
	    out_fl="$OPTARG"
	    ;;
	\?)
	    echo "$0: unknown option $OPTARG" 1>&2
	    exit 1
	    ;;
    esac
done

if test $x_min; then check_num "x_min" $x_min; fi
if test $x_max; then check_num "x_max" $x_max; fi
if test $y_min; then check_num "y_min" $y_min; fi
if test $y_max; then check_num "y_max" $y_max; fi
check_num "display width" $doc_width
check_num "font size" $font_sz
check_num "legend width" $legend_width
check_num "top margin" $top
check_num "left margin" $left

shift `expr $OPTIND - 1`
if [ $# -ne 4 ]
then
    {
	printf '$0 [-f] [-b bounds] [-w pixels] [-z pixels] [-l pixels]\n'
	printf '    [-m top=pixels[,left=pixels]]\n'
	printf '    -- data_type colors_file sweep_angle volume_file\n'
	printf 'where:\n'
	printf '  -f          => fill gaps between adjacent rays.\n'
	printf '  -b          => limits of plot in plot coordinates (not\n'
	printf '                 display coordinates). bounds must be a\n'
	printf '                 string of form\n'
	printf '                 x_min=val,x_max=val,y_min=val,y_max=val\n'
	printf '                 Does not have to give all values. For values\n'
	printf '                 not given, default is to use sweep bounds.\n'
	printf '  -w          => document width, pixels\n'
	printf '  -z          => font size, pixels\n'
	printf '  -l          => width of color cells in legend, pixels\n'
	printf '  -m          => margins around plot area, given as\n'
	printf '                 top=value,left=value. Right and bottom\n'
	printf '                 margins are determined from font and legend\n'
	printf '                 sizes.\n'
	printf '  -j          => URI of a javascript file\n'
	printf '  -o          => name of output file. If none is given, SVG\n'
	printf '                 output goes to a file with a suitable name.\n'
	printf '                 If output goes to a file, script prints the\n'
	printf '                 name of the file to standard output. If\n'
	printf '                 output file name is "-", SVG goes to\n'
	printf '                 standard output.\n'
	printf '  data_type   => data type e.g. DB_DBZ\n'
	printf '  colors_file => specify color for each data interval. Should\n'
	printf '                 be readable with sigmet_raw outlines.\n.'
	printf '  sweep_angle => desired tilt or azimuth, degrees. Image will\n'
	printf '                 show sweep nearest sweep_angle.\n'
	printf '  volume_file => Sigmet raw product file\n'
	printf '\n'
    } 1>&2
    exit 1
fi
data_type="$1"
color_fl="$2"
sweep_angle="$3"
vol_path="$4"

# Check for color table
if ! test -f "$color_fl"
then
    echo "$0: could not find color file $color_fl" 1>&2
    exit 1
fi

cleanup() {
    if test -f "$vol_path"
    then
	sig_raw exit
	rm -f "$in"
    fi
    rm -f "$pfx_svg" "$color_legend_svg"
}
trap cleanup EXIT QUIT INT KILL

# If vol_path is a regular file, start a sigmet_raw daemon for it.
# If vol_path is a fifo, assume a sigmet_raw daemon is monitoring it.
if test -f "$vol_path"
then
    in=.`basename $vol_path | sed -e 's/\.gz$//' -e 's/\.bz2$//'`.$$.in
    mkfifo $in
    if ! sigmet_raw ${vol_path} $in
    then
	rm -f $in;
	exit 1
    fi
    export SIGMET_RAW_IN=$in
elif test -p "$vol_path"
then
    export SIGMET_RAW_IN=$vol_path
else
    echo $vol_path must be a regular file or fifo. 1>&2
    exit 1
fi

# Create an identifier for the volume.
vol=`sig_raw volume_headers | awk -F \| '
    /vol_start_time/ {
	split($1, dh, " ");
	split(dh[1], ymd, "/");
	yr = ymd[1];
	mon = ymd[2];
	day = ymd[3];
	split(dh[2], hms, ":");
	hr = hms[1];
	min = hms[2];
	sec = hms[3];
    }
    /su_site_name/ {
	site = $1;
    }
    END {
	fmt = "%s_%04d%02d%02d%02d%02d%02.0f\n";
	printf fmt, site, yr, mon, day, hr, min, sec;
    }'`

# Store volume headers
eval `sig_raw vol_hdr`

# Assign sweep bounds to x_min, x_max, y_min, and y_max if not set from
# command line.
sweep_index=`sig_raw near_sweep $sweep_angle`
eval `sig_raw sweep_headers \
	| awk -v i=$sweep_index '
	    {
		sweep_date[$2] = $3;
		sweep_time[$2] = $4;
		sweep_angle[$2] = $5;
	    }
	    END {
		printf "sweep_date=%s;sweep_time=%s;sweep_angle=%s\n", \
			sweep_date[i], sweep_time[i], sweep_angle[i];
	    }
	'`
eval `sig_raw sweep_bnds $sweep_index \
| awk '
    /x_min/ { printf "x_min_bnd=%f\n", $2; }
    /x_max/ { printf "x_max_bnd=%f\n", $2; }
    /y_min/ { printf "y_min_bnd=%f\n", $2; }
    /y_max/ { printf "y_max_bnd=%f\n", $2; }
'`
x_min=${x_min:-${x_min_bnd}}; check_num "sweep x min" $x_min
x_max=${x_max:-${x_max_bnd}}; check_num "sweep x max" $x_max
y_min=${y_min:-${y_min_bnd}}; check_num "sweep y min" $y_min
y_max=${y_max:-${y_max_bnd}}; check_num "sweep y max" $y_max
check_num "sweep x min" $x_min
check_num "sweep x max" $x_max
check_num "sweep y min" $y_min
check_num "sweep y max" $y_max
sweep_width=`echo "$x_max - $x_min" | bc -l`
sweep_height=`echo "$y_max - $y_min" | bc -l`

# Determine remaining dimensions of document and plot
# top1 holds specified height of top margin plus space for caption
top1=`echo "$top + 3 * $font_sz" | bc -l`
right=`echo "$legend_width + 8 * $font_sz" | bc -l`
bottom=`echo "6 * $font_sz" | bc -l`
plot_width=`echo "$doc_width - $left - $right" | bc -l`
plot_height=`echo "$plot_width * $sweep_height / $sweep_width" | bc -l`
doc_height=`echo "$plot_height + $top1 + $bottom" | bc -l`
legend_height=`echo "$plot_height * 0.75" | bc -l`

# Axis labels, depend on scan type
if [ "$scan_mode" = "rhi" ]
then
    x_label='Distance down range (m)'
else
    x_label='East-west (m)'
fi
if [ "$scan_mode" = "rhi" ]
then
    y_label='Height (m)'
else
    y_label='North-south (m)'
fi

# Put SVG code for caption and optional Javascript link into a prefix file
c1="$data_type from ${site_name} "
c2="at $radar_lon deg lon, $radar_lat deg lat, "
c3="$sweep_date $sweep_time. "
if [ "$scan_mode" = "rhi" ]
then
    c4="RHI az = $sweep_angle deg."
else
    c4="PPI tilt = $sweep_angle deg."
fi
caption="${c1}${c2}${c3}${c4}"
x_px=`echo "$left + 3 * $font_sz" | bc -l`
y_px=`echo "$top + 2 * $font_sz" | bc -l`
pfx_svg=".${vol}.pfx.$$.in"
mkfifo $pfx_svg
{
    printf '<text id="caption" x="%f" y="%f">%s</text>\n\n' \
	    $x_px $y_px "$caption"
    if test $js_fl
    then
	printf '<script type="application/ecmascript"'
	printf ' xlink:href="%s" />\n\n' $js_fl
    fi
} > $pfx_svg &

# Make a file, acutally a fifo, with SVG code for the color legend.
x_px=`echo "$left + $plot_width + 18" | bc -l`
y_px=`echo "$top + 9" | bc -l`
color_legend_svg=".${vol}.${data_type}.$$.in"
mkfifo $color_legend_svg
{
    printf '<g\n'
    printf '    id="color_legend"\n'
    printf '    transform="translate(%f,%f)">\n' $x_px $y_px
    color_legend $legend_width $legend_height $font_sz < $color_fl
    printf '</g>\n'
} > $color_legend_svg &

outlines() {
    sig_raw outlines $fill $bnds $data_type $color_fl $sweep_index	\
	| sigmet_svg.awk						\
	| pisa -l $left -r $right -t $top1 -b $bottom			\
		-w $doc_width -f $font_sz -m $prx -n $prx		\
		-X "$x_label" -Y "$y_label"				\
		-p "$pfx_svg" -s "$color_legend_svg"			\
		-- $x_min $x_max $y_min $y_max
}
if ! test "$out_fl"
then
    out_fl=`printf "%s_%s_%.1f.svg" $vol $data_type $sweep_angle`
fi
if [ "$out_fl" = "-" ]
then
    outlines
else
    outlines > $out_fl
    echo $out_fl
fi

cleanup
trap - EXIT
exit 0
