#!/bin/sh
#
#	sigmet_ppi_kml --
#		Print a kml file for a sigmet PPI.
#
# Usage:
#	sigmet_kml proj socket
# where:
#	proj		- command that reads longitude latitude pairs from
#			  standard input and prints map coordinates, in meters.
#	socket		- socket that accesses a sigmet_raw daemon
# Optional environment variables SIGMET_RAW_KML_NAME and SIGMET_RAW_KML_DESC
# will be copied to the <name> and <description> elements of the kml file.
#
# Copyright (c) 2011, Gordon D. Carrie. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#     * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please send feedback to dev0@trekix.net

if [ $# -ne 2 ]
then
    echo "Usage: $0 proj socket"
    exit 1
fi
proj="$1"
sock="$2"

# Make sure volume is ppi
if ! { sigmet_raw vol_hdr "$sock" | grep -q 'scan_mode=.*ppi'; }
then
    echo "Volume at "$sock" is not a PPI"
    exit 1
fi

# KML format
kml_tmpl='<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <GroundOverlay>
    <name>%s</name>
    <description>%s</description>
    <LatLonBox>
      <north>%.5f</north>
      <south>%.5f</south>
      <west>%.5f</west>
      <east>%.5f</east>
    </LatLonBox>
    <Icon></Icon>
  </GroundOverlay>
</kml>'

# Create kml file
eval `sigmet_ppi_bnds "$proj" "$sock"`
printf "$kml_tmpl" "SIGMET_RAW_KML_NAME" "SIGMET_RAW_KML_DESC" \
	$north $south $west $east
